package exception_Handling;

public class TestFinally2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("1");
		try {
			
		}

	}
	private static void testMe() {
		try {
			System.out.println("inside method try");
			String [] ss = {"aa","bb"};
			Sys
		}
	}
}
