package exception_Handling;

public class TestFinally1 {
	public static void main (String args []) {
		System.out.println("1");
		try {
			
		}
	}
	private static void testMe() {
		try {
			System.out.println("in method try block");
			String [] s = {"aa","bb"};
			System.out.println(s[0]);
			boolean flag = false;
			if(flag)
				return;
			System.out.println("end of try");
			
		}
		finally {
			System.out.println("inside finally ");
		}
	}
}
